{
 "title": "F5-Load-Balance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "influxdb" },
   {
    "name": "Hostname",
    "query": "SHOW TAG VALUES FROM \"exec4_F5_CPU\" WITH KEY=hostname"
   },
   {
    "name": "VirtualServer",
    "query": "show tag values FROM \"exec4_F5_VirtualStatus\" with key =\"ltmVirtualServStatName\" WHERE hostname =~ /$Hostname/"
   },
   {
    "name": "Pools",
    "query": "SHOW TAG VALUES FROM \"exec4_F5_PoolStatus\" WITH KEY =\"ltmPoolStatName\" WHERE hostname =~ /$Hostname/"
   },
   {
    "name": "Interfaces",
    "query": "show tag values FROM \"exec4_F5_interface\" with key =\"ifDescr\" WHERE hostname =~ /$Hostname/"
   }
  ]
 },
 "panels": [
  {
   "title": "00 - System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Hostname - 設定狀態",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "DAY" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_system",
       "select": [
        [
         { "params": [ "F5_uptime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 8640000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "$Hostname - 狀態",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_system",
       "select": [
        [
         { "params": [ "F5_Device_status" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "$Hostname - 設定狀態",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_system",
       "select": [
        [
         {
          "params": [
           "F5_Synchronization_status_color"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "$Hostname - 溫度",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "度" } },
     "yaxes": [
      { "format": "度" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_system",
       "select": [
        [
         { "params": [ "F5_Temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "$Hostname - 設定狀態",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_system",
       "select": [
        [
         {
          "params": [
           "F5_Synchronization_status_color"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "$Hostname - 設定狀態-OOO",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_system",
       "select": [
        [
         {
          "params": [
           "F5_Synchronization_status_color"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "$Hostname - 記憶體使用量",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_Memory_Usage",
       "select": [
        [
         { "params": [ "sysMultiHostTotal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "sysMultiHostUsed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Used" ], "type": "alias" }
        ],
        [
         { "params": [ "sysMultiHostOtherMemoryUsed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Other-Used" ], "type": "alias" }
        ],
        [
         { "params": [ "sysMultiHostSwapUsed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Swap" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU - $Hostname",
     "type": "graph",
     "description": "#dsfdfs",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "%" }
     ],
     "targets": [
      {
       "alias": "$Hostname - $tag_sysMultiHostCpuHostId : $tag_sysMultiHostCpuIndex",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "sysMultiHostCpuIndex" ], "type": "tag" },
        { "params": [ "sysMultiHostCpuHostId" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_CPU",
       "select": [
        [
         { "params": [ "sysMultiHostCpuUsageRatio1m" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "01 - 連線數",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Hostname - VIP 連線數圖 : $VirtualServer",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$Hostname - $VirtualServer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_VirtualStatus",
       "select": [
        [
         {
          "params": [
           "ltmVirtualServStatClientCurConns"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
        { "condition": "AND", "key": "ltmVirtualServStatName", "operator": "=~", "value": "/^$VirtualServer$/" }
       ]
      }
     ]
    },
    {
     "title": "$Hostname - VIP 流量監控圖 : $VirtualServer",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$Hostname  - $VirtualServer  - IN",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_VirtualStatus",
       "select": [
        [
         {
          "params": [
           "ltmVirtualServStatClientBytesIn"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
        { "condition": "AND", "key": "ltmVirtualServStatName", "operator": "=~", "value": "/^$VirtualServer$/" }
       ]
      },
      {
       "alias": "$Hostname  - $VirtualServer  - OUT",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_VirtualStatus",
       "select": [
        [
         {
          "params": [
           "ltmVirtualServStatClientBytesOut"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
        { "condition": "AND", "key": "ltmVirtualServStatName", "operator": "=~", "value": "/^$VirtualServer$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "02 - 監控圖",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Hostname Poolmember - 連線數  $Pools",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ltmPoolMemberStatNodeName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ltmPoolMemberStatNodeName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_PoolMembers_Status",
       "select": [
        [
         {
          "params": [
           "ltmPoolMemberStatServerCurConns"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
        { "condition": "AND", "key": "ltmPoolMemberStatPoolName", "operator": "=~", "value": "/^$Pools$/" }
       ]
      }
     ]
    },
    {
     "title": "$Hostname Pool - 連線數  $Pools",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$Hostname - $Pools",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_PoolStatus",
       "select": [
        [
         { "params": [ "ltmPoolStatServerCurConns" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
        { "condition": "AND", "key": "ltmPoolStatName", "operator": "=~", "value": "/^$Pools$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "03 - 測試",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Hostname Poolmember - 流量  $Pools",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_ltmPoolMemberStatNodeName - IN",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ltmPoolMemberStatNodeName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_PoolMembers_Status",
       "select": [
        [
         { "params": [ "ltmPoolMemberStatServerBytesIn" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
        { "condition": "AND", "key": "ltmPoolMemberStatPoolName", "operator": "=~", "value": "/^$Pools$/" }
       ]
      },
      {
       "alias": "$tag_ltmPoolMemberStatNodeName - OUT",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ltmPoolMemberStatNodeName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_PoolMembers_Status",
       "select": [
        [
         {
          "params": [
           "ltmPoolMemberStatServerBytesOut"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
        { "condition": "AND", "key": "ltmPoolMemberStatPoolName", "operator": "=~", "value": "/^$Pools$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "04 - Interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Hostname - $Interfaces",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
     "repeat": "Interfaces",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "In - $tag_hostname - $tag_ifDescr",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ifDescr" ], "type": "tag" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_interface",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
        { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$Interfaces$/" }
       ]
      },
      {
       "alias": "Out - $tag_hostname - $tag_ifDescr",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ifDescr" ], "type": "tag" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec4_F5_interface",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
        { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$Interfaces$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}