- name: Setup single big-ip
  hosts: localhost
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "username"
      prompt: "Enter BIG-IP username"
      private: no
    - name: "password"
      prompt: "Enter BIG-IP password"
      private: yes

  tasks:
  - name: Get facts from XLSX file
    xlsx_to_facts:
      src: ./single-bigip_lab.xlsx

  - name: set mgmt IP variable
    set_fact: 
      mgmt_ip: "{{ item.mgmt }}" 
    with_items: "{{ spreadsheet_mgmt }}"

  - debug:
      msg: Server mgmt IP is {{ mgmt_ip }}

  - set_fact:
     provider:
      server: "{{ mgmt_ip }}"
      user: "{{ username}}"
      password: "{{ password }}"
      validate_certs: no
      #server_port: 8443

  - name: Create pools
    bigip_pool:
      provider: "{{ provider }}"
      name: "{{ item.pool_name }}"
      lb_method: "{{ item.lb_method }}"
      slow_ramp_time: "120"
      monitor_type: "{{ item.monitor_type }}"
      monitors: "{{ item.monitors }}"
      state: "{{ item.state }}"
    with_items: "{{ spreadsheet_pools }}"

  - name: Add nodes to pools
    bigip_pool_member:
      provider: "{{ provider }}"
      pool: "{{ item.pool_name }}"
      name: "{{ 'node_' + item.pool_member }}"
      host: "{{ item.pool_member }}"
      port: "{{ item.pool_port }}"
      state: "{{ item.state }}"
    with_items: "{{ spreadsheet_pool_members }}"

