- name: Setup single big-ip
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Get facts from XLSX file
    xlsx_to_facts:
      src: single-bigip_v1.xlsx
    register: result
  
    #  - name: display all facts   # (2)
    #    debug:
    #      msg: "{{ result }}"

  - name: set mgmt IP variable
    set_fact:
      mgmt_ip: "{{ item.mgmt }}"
    with_items: "{{ spreadsheet_mgmt }}"
  
  - debug:
      msg: Server mgmt IP is {{ mgmt_ip }}

