- name: Setup single big-ip
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: single-bigip.xlsx
  
  - name: set mgmt IP variable
    set_fact:
      mgmt_ip: "{{ item.mgmt }}"
    with_items: "{{ spreadsheet_mgmt }}"
  
  - debug:
      msg: Server mgmt IP is {{ mgmt_ip }}

