- name: Setup single big-ip
  hosts: localhost
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "username"
      prompt: "Enter BIG-IP username"
      private: no
    - name: "password"
      prompt: "Enter BIG-IP password"
      private: yes

      #  environment:
      #    F5_USER: "{{ username }}"
      #    F5_PASSWORD: "{{ password }}"
      #    F5_VALIDATE_CERTS: "no"

  tasks:
  - name: Get facts from XLSX file
    xlsx_to_facts:
      src: ./single-bigip_lab.xlsx

  - name: set mgmt IP variable
    set_fact: 
      mgmt_ip: "{{ item.mgmt }}" 
    with_items: "{{ spreadsheet_mgmt }}"

  - debug:
      msg: Server mgmt IP is {{ mgmt_ip }}

  - name: set dns 
    bigip_device_dns:
      provider:
        password: "{{ password }}"
        server: "{{ mgmt_ip }}"
        user: "{{ username }}"
        validate_certs: no
      name_servers: 
        - "{{ item.dns1 }}"
        - "{{ item.dns2 }}"
    with_items: 
      - "{{ spreadsheet_system_settings}}"

    delegate_to: localhost

  - name: set ntp on {{ mgmt_ip }}
    bigip_device_ntp:
      provider:
        password: "{{ password }}"
        server: "{{ mgmt_ip }}"
        user: "{{ username }}"
        validate_certs: no
      ntp_servers:
        - "{{ item.ntp1 }}"
        - "{{ item.ntp2 }}"
        - "{{ item.ntp3 }}"
    delegate_to: localhost
    with_items: 
      - "{{ spreadsheet_system_settings}}"

